// src/config/schema.ts
import { z } from 'zod';

export const ConfigSchema = z.object({
  preset: z.literal('custom'),
  credentials: z.object({
    rpcUrl: z.string().url(),
    walletKey: z.string(),
    heliusApiKey: z.string(),
    telegramBotToken: z.string(),
    telegramChatId: z.string(),
  }),
  llm: z.object({
    baseUrl: z.string().url(),
    apiKey: z.string(),
    model: z.string(),
    managementModel: z.string(),
    screeningModel: z.string(),
    generalModel: z.string(),
    chatModel: z.string(),
    temperature: z.number().min(0).max(2),
    maxTokens: z.number().positive(),
    maxSteps: z.number().positive(),
  }),
  risk: z.object({
    maxPositions: z.number().int().positive(),
    maxDeployAmount: z.number().positive(),
  }),
  screening: z.object({
    timeframe: z.enum(['5m', '15m', '30m', '1h', '4h', '24h']),
    category: z.enum(['trending', 'new', 'volume']),
    minTvl: z.number().positive(),
    maxTvl: z.number().positive(),
    minVolume: z.number().positive(),
    minOrganic: z.number().min(0).max(100),
    minHolders: z.number().int().positive(),
    minMcap: z.number().positive(),
    maxMcap: z.number().positive(),
    minBinStep: z.number().int().positive(),
    maxBinStep: z.number().int().positive(),
    minFeeActiveTvlRatio: z.number().positive(),
    minTokenFeesSol: z.number().positive(),
    maxBundlersPct: z.number().min(0).max(100),
    maxTop10Pct: z.number().min(0).max(100),
    blockedLaunchpads: z.array(z.string()),
  }),
  management: z.object({
    strategy: z.enum(['spot', 'curve', 'bid_ask', 'single_sided_reseed', 'fee_compounding', 'partial_harvest']),
    binsBelow: z.number().int().positive(),
    binsAbove: z.number().int().positive(),
    deployAmountSol: z.number().positive(),
    minSolToOpen: z.number().positive(),
    gasReserve: z.number().positive(),
    positionSizePct: z.number().min(0).max(100),
    takeProfitFeePct: z.number().positive(),
    emergencyPriceDropPct: z.number().negative(),
    outOfRangeWaitMinutes: z.number().int().positive(),
    outOfRangeBinsToClose: z.number().int().positive(),
    minClaimAmount: z.number().positive(),
    minVolumeToRebalance: z.number().positive(),
    minFeePerTvl24h: z.number().positive(),
    autoSwapAfterClaim: z.boolean(),
  }),
  telegram: z.object({
    authorizedChatIds: z.array(z.string()),
    chatHistoryLimit: z.number().int().positive().default(20),
    approvalTimeoutMs: z.number().positive().default(300000),
    rateLimitPerSecond: z.number().positive().default(0.5),
    rateLimitPerHour: z.number().int().positive().default(100),
  }),
  schedule: z.object({
    managementIntervalMin: z.number().positive(),
    screeningIntervalMin: z.number().positive(),
    evolutionIntervalHours: z.number().positive(),
    healthCheckIntervalMin: z.number().positive(),
  }),
  runtime: z.object({
    dryRun: z.boolean(),
    logLevel: z.enum(['trace', 'debug', 'info', 'warn', 'error']),
  }),
  _lastEvolved: z.string().optional(),
  _lastAgentTune: z.string().optional(),
});

export type Config = z.infer<typeof ConfigSchema>;
